### ISSUE TITLE
dwarf_export 

### ISSUE THREAD

**Issue by kotee4ko** [Vector35/dwarf_import#11]
Hello. 

BN - one of the best platform for linux pwn and reverse engineering. 
I spent much time trying to make something like "reverse unstripping"  for elf binary.

Both ghidra and ida have solutions - ghidra2dwarf and dwarfexport respectively. 
Firs one doesn't handle large (7mb) elfs, second - doesn't support last versions of IDA.
I was able to made adaptation of last one for idasdk 7.5, but only for linux. I don't have IDA PRO for linux.

So, fact: the best decompiled, human readable code I achieve with BN. Speaking true - I do some cheating with importing some C++ symbols from IDA to BN, but finally - BN gives me the best result.

So, my question is: how to *EXPORT* (generate) dwarf from BN project?

With respect.

**Comment by KyleMiles** [comment]
Unfortunately we do not support this nor do I believe we plan to.

That said, it's entirely possible to write a plugin to do exactly what you want, and it'd be a welcome addition to our [Community Plugins](https://github.com/Vector35/community-plugins) repo.

Some implementation insight:
 - You'd be best off using a library that can write DWARF files for you rather than writing your own.
 - You likely won't be able to support line numbers.
 - The hardest part will probably be converting Binary Ninja's types into DWARF types, but not impossible.

**Comment by KyleMiles** [comment]
Also, in regards to C++ symbols, check out the setting `analysis.types.TemplateSimplifier` or `Analysis -> Simplify Templates`

**Comment by psifertex** [comment]
Also, if the goal is merely interoperability with other tools, you might consider one of the following plugins instead: 

https://github.com/lunixbochs/revsync
https://github.com/zznop/bnida

I'm curious what your end-goal behind emitting dwarf information in binaries is?

**Comment by kotee4ko** [comment]
Appreciated!

My goal is use full power of GDB while debug.
Traces. Scripts. Just understanding where am I and what's going on :)
